source "https://rubygems.org"

gem "berkshelf"
gem "chef"
gem "chefspec"
gem "foodcritic"
gem "rake"
gem "rspec"
gem "winrm-transport"
gem "winrm"
gem "test-kitchen"
gem "kitchen-vagrant"
gem "vagrant-wrapper"
gem "stove"
