name             'hurry-up-and-test'
maintainer       'Matt Wrock'
maintainer_email 'matt@mattwrock.com'
license          'Apache 2.0'
description      'Recipes to help with testing'
version          '0.1.2'
source_url       'https://github.com/mwrock/hurry-up-and-test'

supports         'ubuntu'
supports         'centos'
supports         'windows'
