name             'hurry-up-and-test-tests'
maintainer       'Matt Wrock'
maintainer_email 'matt@mattwrock.com'
license          'Apache 2.0'
description      'tests the recipes of hurry-up-and-test'
version          '0.1.0'
